---
- name: Update Package cache on all managed servers
  hosts: servers
  become: true
  gather_facts: true

  tasks:
    - name: Ensure APT package cache is updated
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- name: Teceon-orbax Application Compliance
  hosts: servers
  become: true
  gather_facts: false

  vars_files:
    - ../inventory/application.yaml
    - ../inventory/install-tool.yaml

  tasks:
    - name: Run Application Compliance Check
      ansible.builtin.import_tasks: ../tasks/application.yaml

    - name: Tool Installation
      ansible.builtin.import_tasks: ../tasks/install-tool.yaml

    - name: Generate Application Compliance Report
      ansible.builtin.import_tasks: ../tasks/report.yaml

